export const GET_DATE_DETAILS_REQUEST = 'GET_DATE_DETAILS_REQUEST'
export const GET_DATE_DETAILS_SUCCESS = 'GET_DATE_DETAILS_SUCCESS'
export const GET_DATE_DETAILS_FAIL = 'GET_DATE_DETAILS_FAIL'

export const GET_BOOKED_DETAILS = 'GET_BOOKED_DETAILS'
export const GET_BOOKED_DETAILS_SUCESS = 'GET_BOOKED_DETAILS_SUCESS'
export const GET_BOOKED_DETAILS_FAIL = 'GET_BOOKED_DETAILS_FAIL'

export const GET_SEATS_AND_TOTAL_AMOUNT = 'GET_SEATS_AND_TOTAL_AMOUNT'
export const GET_SEATS_AND_TOTAL_AMOUNT_FAIL = 'GET_SEATS_AND_TOTAL_AMOUNT_FAIL'

export const ADD_TOTAL_AMOUNT_WHICH_BOOKED = 'ADD_TOTAL_AMOUNT_WHICH_BOOKED'
export const ADD_TOTAL_AMOUNT_WHICH_BOOKED_FAIL = 'ADD_TOTAL_AMOUNT_WHICH_BOOKED_FAIL'

export const ADD_BOOKING_DETAILS = 'ADD_BOOKING_DETAILS'
export const ADD_BOOKING_DETAILS_SUCCESS = 'ADD_BOOKING_DETAILS_SUCCESS'
export const ADD_BOOKING_DETAILS_FAIL = 'ADD_BOOKING_DETAILS_FAIL'

export const GET_SEATS_INFORMATION_REQUEST = 'GET_SEATS_INFORMATION_REQUEST'
export const GET_SEATS_INFORMATION_SUCCESS = 'GET_SEATS_INFORMATION_SUCCESS'
export const GET_SEATS_INFORMATION_FAIL = 'GET_SEATS_INFORMATION_FAIL'

export const ADD_DATE_AND_DAY_TO_STATE = 'ADD_DATE_AND_DAY_TO_STATE'
export const ADD_DATE_AND_DAY_TO_STATE_FAIL = 'ADD_DATE_AND_DAY_TO_STATE_FAIL'