export const GET_MOVIE_REQUEST = 'GET_MOVIE_REQUEST'
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';
export const GET_MOVIE_FAIL = 'GET_MOVIE_FAIL';

export const GET_MOVIE_INFO_MOVIEPAGE_REQUEST = 'GET_MOVIE_INFO_MOVIEPAGE_REQUEST'
export const GET_MOVIE_INFO_MOVIEPAGE_SUCCESS = 'GET_MOVIE_INFO_MOVIEPAGE_SUCCESS';
export const GET_MOVIE_INFO_MOVIEPAGE_FAIL = 'GET_MOVIE_INFO_MOVIEPAGE_FAIL';


