export const GET_MOVIE_REQUEST = 'GET_MOVIE_REQUEST'
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';
export const GET_MOVIE_FAIL = 'GET_MOVIE_FAIL';

export const GET_MOVIE_INFO_MOVIEPAGE_REQUEST = 'GET_MOVIE_INFO_MOVIEPAGE_REQUEST'
export const GET_MOVIE_INFO_MOVIEPAGE_SUCCESS = 'GET_MOVIE_INFO_MOVIEPAGE_SUCCESS';
export const GET_MOVIE_INFO_MOVIEPAGE_FAIL = 'GET_MOVIE_INFO_MOVIEPAGE_FAIL';

export const GET_MOVIE_ID_REQUEST = 'GET_MOVIE_ID_REQUEST'
export const GET_MOVIE_ID_SUCCESS = 'GET_MOVIE_ID_SUCCESS';
export const GET_MOVIE_ID_FAIL = 'GET_MOVIE_ID_FAIL';

export const ADD_MOVIE_REVIEW_REQUEST = 'ADD_MOVIE_REVIEW_REQUEST'
export const ADD_MOVIE_REVIEW_SUCCESS = 'ADD_MOVIE_REVIEW_SUCCESS';
export const ADD_MOVIE_REVIEW_FAIL = 'ADD_MOVIE_REVIEW_FAIL';

export const GET_MOVIE_REVIEW_BY_ID_REQUEST = 'GET_MOVIE_REVIEW_BY_REQUEST'
export const GET_MOVIE_REVIEW_BY_ID_SUCCESS = 'GET_MOVIE_REVIEW_BY_ID_SUCCESS';
export const GET_MOVIE_REVIEW_BY_ID_FAIL = 'GET_MOVIE_REVIEW_BY_ID_FAIL';


