export const THEATER_LOGIN_REQUEST = 'THEATER_LOGIN_REQUEST'
export const THEATER_LOGIN_SUCCESS = 'THEATER_LOGIN_SUCCESS';
export const THEATER_LOGIN_FAIL = 'THEATER_LOGIN_FAIL';

export const THEATER_FETCH_REQUEST = 'THEATER_FETCH_REQUEST'
export const THEATER_FETCH_SUCCESS = 'THEATER_FETCH_SUCCESS';
export const THEATER_FETCH_FAIL = 'THEATER_FETCH_FAIL';

export const THEATER_APPROVE_REQUEST = 'THEATER_APPROVE_REQUEST'
export const THEATER_APPROVE_SUCCESS = 'THEATER_APPROVE_SUCCESS';
export const THEATER_APPROVE_FAIL = 'THEATER_APPROVE_FAIL';

export const THEATER_SCREENADD_REQUEST = 'THEATER_SCREENADD_REQUEST'
export const THEATER_SCREENADD_SUCESS = 'THEATER_SCREENADD_SUCESS';
export const THEATER_SCREENADD_FAIL = 'THEATER_SCREENADD_FAIL';

export const GET_SCREEN_LIST_REQUEST = 'GET_SCREEN_LIST_REQUEST'
export const GET_SCREEN_LIST_SUCCESSS = 'GET_SCREEN_LIST_SUCCESSS';
export const GET_SCREEN_LIST_FAIL = 'GET_SCREEN_LIST_FAIL';

